---
language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
  - node_modules
install: true
script:
 - 'if [ $TEST_SUITE = "default" ]; then tasks/e2e-default.sh; fi'
env:
  global:
    - USE_YARN=no
  matrix:
    - TEST_SUITE=default