---
language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
  - node_modules
install: true
script:
 - 'if [ $TEST_SUITE = "default" ]; then tasks/e2e-default.sh; fi'
env:
  global:
    - USE_YARN=no
  matrix:
    - TEST_SUITE=default
matrix:
  include:
    - node_js: 0.10
      env: TEST_SUITE=simple
    - node_js: 6
      env: USE_YARN=yes TEST_SUITE=simple